# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0002_auto_20160206_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.CharField(default='local', max_length=100),
        ),
    ]
