# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0002_auto_20160206_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visibilty',
            new_name='visibility',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contentType',
        ),
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
