# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0006_author_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
