# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0007_auto_20160206_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('host', models.CharField(default='local', max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='images/profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
