# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0008_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
