# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0009_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
