# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainp2p', '0013_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
