# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0014_author_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='username',
        ),
    ]
