# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0015_auto_20160226_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='username',
            new_name='user',
        ),
    ]
