# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0016_auto_20160226_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/post'),
        ),
    ]
