# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0019_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
