# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainp2p', '0020_auto_20160304_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, default='images/profile/default-avatar.jpg', null=True, upload_to='images/profile'),
        ),
    ]
