# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialp2p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='http://socialp2p.herokuapp.com/', max_length=100),
        ),
    ]
