# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 22:08
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialp2p', '0003_auto_20160308_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='http://socialp2p.herokuapp.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_can_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'PUBLIC'), ('FOF', 'FOAF'), ('FRS', 'FRIENDS'), ('PRV', 'PRIVATE'), ('SVO', 'SERVERONLY')], default='PRV', max_length=3),
        ),
    ]
