# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialp2p', '0003_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Public'), ('FOF', 'Friends Of Friends'), ('FRS', 'Friends'), ('PRV', 'Only Me'), ('ONL', 'Only This Person ...'), ('LFS', 'Local Friends'), ('SVO', 'Server Only')], default='PRV', max_length=3),
        ),
    ]
