# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialp2p', '0004_auto_20160320_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Public to All'), ('SVO', 'Public to Local'), ('FOF', 'Friends of Friends'), ('FRS', 'Friends'), ('LFS', 'Local Friends'), ('ONL', 'Only This Person ...'), ('PRV', 'Only Me')], default='PRV', max_length=3),
        ),
    ]
