# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialp2p', '0004_auto_20160310_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 11, 0, 45, 44, 446302, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
