# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('socialp2p', '0006_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='access_password',
            field=models.CharField(default='socialp2p', max_length=100, verbose_name=django.forms.widgets.PasswordInput),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='access_username',
            field=models.CharField(default='socialp2p', max_length=100),
            preserve_default=False,
        ),
    ]
