# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialp2p', '0010_auto_20160321_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
